version: '3.8'

services:
 database_mongo:                                       # сервис для базы данных mongodb
    image: mongo:latest                         # напрямую выбираем нужный образ mongodb
    container_name: database_mongo     # название контейнера
    volumes:                                    # хранилища
      - ./mongodb_api:/data/db
    ports:
      - 27017:27017